# Generated by Django 5.0.3 on 2025-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0002_clubs_user_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image',
        ),
        migrations.AddField(
            model_name='events',
            name='main_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='events',
            name='promo_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
