# Generated by Django 5.0.3 on 2025-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0003_remove_events_image_events_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='vip_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='vip_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='vip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
