# Generated by Django 5.0.3 on 2025-01-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0004_events_vip_capacity_events_vip_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='promo_image',
        ),
    ]
