# Generated by Django 5.0.3 on 2025-01-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0005_remove_events_promo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_at',
            field=models.DateTimeField(),
        ),
    ]
