# Generated by Django 5.0.3 on 2025-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0006_alter_events_event_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='nquantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='vquantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
