# Generated by Django 5.0.3 on 2025-01-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0007_remove_cart_quantity_cart_nquantity_cart_vquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nquantity', models.IntegerField(blank=True, null=True)),
                ('vquantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightapp.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nightapp.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
