# Generated by Django 5.0.3 on 2025-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0008_remove_orders_user_booking_delete_cart_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
