# Generated by Django 5.0.3 on 2025-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0009_events_artist_events_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='vip',
        ),
        migrations.AddField(
            model_name='events',
            name='vip_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_category',
            field=models.CharField(choices=[('music', 'Music'), ('comedy', 'Comedy'), ('dance', 'Dance'), ('theatre', 'Theatre'), ('sports', 'Sports'), ('conference', 'Conference'), ('exhibition', 'Exhibition'), ('festival', 'Festival'), ('party', 'Party'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='vip_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='vip_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
