# Generated by Django 5.0.3 on 2025-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0010_remove_events_vip_events_vip_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
