# Generated by Django 5.1.6 on 2025-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0011_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
