# Generated by Django 5.1.6 on 2025-03-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightapp', '0012_events_lattitude_events_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
